### ISSUE TITLE
Mandatory stopwords downloading

### ISSUE THREAD

**Issue by maybe-hello-world** [obi-1-konobe/information_retrieval_index#1]
https://github.com/obi-1-konobe/information_retrieval_index/blob/1ea08078a8c1f28febb29082121f8391c55a29bc/preprocess.py#L9

It's better to migrate this from global scope (and running during import) to function ('cause I could want to use only process_query function from your library and do not want to download MBs of data)

**Comment by obi-1-konobe** [comment]
fixed
